'use client';
import { useEffect, useId, useRef, useState } from 'react';
import { DEMO_OTP, digits, persianDigits } from '../lib/forms';
export function OtpField({ value, onChange, error, label = 'کد تأیید ۶ رقمی' }: { value:string;onChange:(v:string)=>void;error?:string;label?:string }) {
  const [seconds,setSeconds]=useState(105); const inputs=useRef<(HTMLInputElement|null)[]>([]);const help=useId();
  useEffect(()=>{if(!seconds)return;const id=setTimeout(()=>setSeconds(s=>s-1),1000);return()=>clearTimeout(id);},[seconds]);
  function enter(raw:string,i:number){const next=digits(raw);if(next.length>1){const chars=(value.slice(0,i)+next).slice(0,6);onChange(chars);inputs.current[Math.min(chars.length,5)]?.focus();return;}const chars=value.padEnd(6,' ').split('');chars[i]=next||' ';onChange(chars.join('').slice(0,6).trimEnd());if(next)inputs.current[Math.min(i+1,5)]?.focus();}
  return <div className="otp-verification"><div className="otp-boxes" role="group" aria-label={label} dir="ltr">{Array.from({length:6},(_,i)=><input key={i} ref={el=>{inputs.current[i]=el;}} aria-label={`رقم ${persianDigits(String(i+1))} کد تأیید`} aria-invalid={!!error} aria-describedby={error?help:undefined} value={persianDigits((value[i]||'').trim())} inputMode="numeric" autoComplete={i===0?'one-time-code':'off'} onFocus={e=>e.target.select()} onChange={e=>enter(e.target.value,i)} onPaste={e=>{e.preventDefault();enter(e.clipboardData.getData('text'),i);}} onKeyDown={e=>{if(e.key==='Backspace'&&!(value[i]||'').trim()&&i>0){e.preventDefault();const chars=value.padEnd(6,' ').split('');chars[i-1]=' ';onChange(chars.join('').trimEnd());inputs.current[i-1]?.focus();}if(e.key==='ArrowLeft'&&i>0)inputs.current[i-1]?.focus();if(e.key==='ArrowRight'&&i<5)inputs.current[i+1]?.focus();}} />)}</div>{error&&<p id={help} className="camera-error" role="alert">{error}</p>}<button type="button" className="otp-resend" disabled={seconds>0} onClick={()=>{setSeconds(105);onChange('');inputs.current[0]?.focus();}}>{seconds?`ارسال مجدد تا ${persianDigits(String(Math.floor(seconds/60)).padStart(2,'0'))}:${persianDigits(String(seconds%60).padStart(2,'0'))}`:'ارسال مجدد کد'}</button><button type="button" className="demo-fill otp-demo" onClick={()=>onChange(DEMO_OTP)}>کد آزمایشی: ۱۲۳۴۵۶</button></div>;
}
