'use client';
import { useEffect, useRef, useState } from 'react';
import type { ActivityEvent } from '../lib/activity';
import { digits, money, DEMO_OTP } from '../lib/forms';
import { isValidCardOtp } from '../lib/card-otp';
import { DynamicOtpField } from './DynamicOtpField';
import { FlowShell } from './FlowShell';
import { Icon } from './Icon';
import { MaterialField } from './MaterialField';
import { SuccessAnimation } from './SuccessAnimation';
import { ActionButton } from './ui/ActionButton';

type Step = 'amount' | 'gateway' | 'processing' | 'success';
export function TopUpFlow({ onClose, onComplete }: { onClose: () => void; onComplete: (event: ActivityEvent) => void }) {
  const [step, setStep] = useState<Step>('amount');
  const [amount, setAmount] = useState(''); const [card, setCard] = useState(''); const [cvv, setCvv] = useState('');
  const [month, setMonth] = useState(''); const [year, setYear] = useState(''); const [password, setPassword] = useState('');
  const [otpRequested, setOtpRequested] = useState(false); const [error, setError] = useState(''); const recorded = useRef(false);
  const numericAmount = Number(amount); const validAmount = Number.isSafeInteger(numericAmount) && numericAmount >= 100000 && numericAmount <= 500000000;
  const cardDisplay = card.replace(/(\d{4})(?=\d)/g, '$1 ');

  useEffect(() => { if (step !== 'processing') return; const timer = window.setTimeout(() => { if (!recorded.current) { recorded.current = true; onComplete({ title: 'افزایش موجودی', value: `${money(numericAmount)} ریال`, icon: 'plus', details: [['حساب مقصد', 'هزینه‌های روزمره'], ['شماره پیگیری', '۸۴۶۲۹۱۷۵۳۰'], ['روش پرداخت', 'درگاه پرداخت اینترنتی']] }); } setStep('success'); }, 1100); return () => window.clearTimeout(timer); }, [step, numericAmount, onComplete]);
  function back() { if (step === 'processing') return; if (step === 'gateway') { setError(''); setStep('amount'); } else onClose(); }
  function pay() { const validOtp = isValidCardOtp(password) || otpRequested && password === DEMO_OTP; if (card.length !== 16 || !/^\d{3,4}$/.test(cvv) || !/^(0[1-9]|1[0-2])$/.test(month) || !/^\d{2}$/.test(year) || !validOtp) { setError('اطلاعات کارت و رمز پویا را کامل کنید. برای نسخهٔ آزمایشی می‌توانید از تکمیل خودکار استفاده کنید.'); return; } setError(''); setStep('processing'); }
  function fillDemo() { setCard('6219861910111213'); setCvv('123'); setMonth('07'); setYear('08'); setPassword(DEMO_OTP); setOtpRequested(true); setError(''); }

  const titles: Record<Step, string> = { amount: 'افزایش موجودی', gateway: 'پرداخت', processing: 'در حال پرداخت', success: 'رسید افزایش موجودی' };
  return <FlowShell variant="transfer-compact internal-flow topup-flow" title={titles[step]} subtitle={step === 'amount' ? 'مبلغ موردنظر را به حساب خود اضافه کنید.' : undefined} stepKey={step} onBack={back} onClose={onClose}>
    {step === 'processing' && <div className="processing-panel" role="status"><div className="processing-spinner" /><h2>در حال تأیید پرداخت</h2><p>هیچ درخواستی به شبکهٔ بانکی ارسال نمی‌شود.</p></div>}
    {step === 'success' && <><section className="topup-receipt"><SuccessAnimation /><span className="receipt-status">پرداخت نمایشی موفق</span><h2>موجودی افزایش یافت</h2><div className="topup-success-amount"><b>+{money(numericAmount)}</b><Icon name="rial" size={22} /></div><dl><div><dt>حساب مقصد</dt><dd>هزینه‌های روزمره</dd></div><div><dt>شماره پیگیری</dt><dd>۸۴۶۲۹۱۷۵۳۰</dd></div><div><dt>روش پرداخت</dt><dd>درگاه اینترنتی</dd></div><div><dt>زمان پرداخت</dt><dd>همین حالا</dd></div></dl><p className="sheet-note">این رسید و پرداخت صرفاً نمایشی است.</p></section><ActionButton className="flow-button" onClick={onClose}>بازگشت به خانه</ActionButton></>}
    {step === 'gateway' && <><section className="topup-gateway-head"><span className="gateway-shield">✓</span><div><strong>درگاه پرداخت امن</strong><small>شبکه پرداخت تایم · نسخهٔ آزمایشی</small></div><b>۰۹:۵۹</b></section><section className="topup-invoice"><div><small>پذیرنده</small><strong>تایم‌بانک</strong></div><div><small>مبلغ پرداخت</small><strong>{money(numericAmount)} ریال</strong></div></section><section className="topup-surface"><p className="gateway-warning">اطلاعات واقعی کارت را وارد نکنید. این درگاه فقط جریان پرداخت را نمایش می‌دهد.</p><button className="demo-fill" onClick={fillDemo}>تکمیل اطلاعات آزمایشی</button><div className="flow-form"><MaterialField label="شماره کارت" value={cardDisplay} dir="ltr" inputMode="numeric" maxLength={19} onChange={event => setCard(digits(event.target.value).slice(0, 16))} /><div className="credentials-row"><MaterialField label="CVV2" value={cvv} type="password" dir="ltr" inputMode="numeric" maxLength={4} onChange={event => setCvv(digits(event.target.value))} /><div className="field-pair"><MaterialField label="ماه" value={month} dir="ltr" inputMode="numeric" maxLength={2} onChange={event => setMonth(digits(event.target.value))} /><MaterialField label="سال" value={year} dir="ltr" inputMode="numeric" maxLength={2} onChange={event => setYear(digits(event.target.value))} /></div></div><DynamicOtpField value={password} onChange={setPassword} onRequest={() => setOtpRequested(true)} /></div>{error && <p className="topup-error" role="alert">{error}</p>}</section><div className="button-stack"><ActionButton className="flow-button" onClick={pay}>پرداخت نمایشی {money(numericAmount)} ریال</ActionButton><ActionButton variant="secondary" className="flow-button secondary" onClick={() => setStep('amount')}>انصراف و بازگشت</ActionButton></div></>}
    {step === 'amount' && <><section className="topup-account"><span className="topup-wallet"><Icon name="plus" size={23} /></span><div><small>واریز به</small><strong>حساب هزینه‌های روزمره</strong><span>مانده فعلی: ۲۴۸٬۵۶۰٬۰۰۰ ریال</span></div></section><section className="topup-surface topup-amount-surface"><MaterialField className="topup-amount-field" label="مبلغ افزایش موجودی" value={amount ? money(numericAmount) : ''} dir="ltr" inputMode="numeric" trailing={<Icon name="rial" size={20} />} onChange={event => setAmount(digits(event.target.value).slice(0, 12))} /><div className="amount-suggestions">{[1000000, 5000000, 10000000].map(value => <button key={value} onClick={() => setAmount(String(value))}>+ {money(value)}</button>)}</div>{amount && !validAmount && <p className="topup-error" role="alert">مبلغ باید بین ۱۰۰٬۰۰۰ تا ۵۰۰٬۰۰۰٬۰۰۰ ریال باشد.</p>}<div className="topup-summary"><div><span>مبلغ واریز</span><strong>{amount ? money(numericAmount) : '۰'} ریال</strong></div><div><span>کارمزد</span><strong>رایگان</strong></div></div></section><ActionButton className="flow-button" disabled={!validAmount} onClick={() => setStep('gateway')}>ادامه و پرداخت</ActionButton><p className="topup-security"><span>✓</span> پرداخت در درگاه امن و آزمایشی انجام می‌شود.</p></>}
  </FlowShell>;
}
