'use client';
import { useEffect, useRef, useState } from 'react';
import { FlowShell } from './FlowShell';
import { MaterialField } from './MaterialField';
import { DynamicOtpField } from './DynamicOtpField';
import { BottomSheet } from './BottomSheet';
import { SuccessAnimation } from './SuccessAnimation';
import { AnimatePresence } from 'motion/react';
import type { ActivityEvent } from '../lib/activity';
import { Icon } from './Icon';
import { isValidCardOtp } from '../lib/card-otp';
import { RecipientAvatar } from './RecipientAvatar';
import { ActionButton } from './ui/ActionButton';
import { ListRow } from './ui/ListRow';
import { DEMO_OTP, digits, money, persianDigits, latinDigits } from '../lib/forms';
import { cleanDestination, destinationIban, destinationKind, formattedDestination, kindLabels, methodDestination, methodError, methods, recipients, sourceAccounts, type DestinationKind, type Method } from '../lib/transfer';
type Step = 'destination'|'amount'|'method'|'confirm'|'processing'|'receipt';
const steps: Step[] = ['destination','amount','method','confirm','processing','receipt'];
export function TransferFlow({ onClose, onComplete }: { onClose: () => void; onComplete:(a:ActivityEvent)=>void }) {
  const [methodOpen,setMethodOpen]=useState(false);
  const [step, setStep] = useState<Step>('destination');
  const [query, setQuery] = useState(''); const [destination, setDestination] = useState(''); const [recipientName, setRecipientName] = useState('گیرندهٔ نمایشی'); const [filter, setFilter] = useState<DestinationKind|'all'>('all');
  const [amountText, setAmountText] = useState(''); const [methodId, setMethodId] = useState(''); const [errors, setErrors] = useState<Record<string,string>>({});
  const [cvv, setCvv] = useState(''); const [month, setMonth] = useState(''); const [year, setYear] = useState(''); const [otp, setOtp] = useState(''); const [otpRequested, setOtpRequested] = useState(false); const [description, setDescription] = useState(''); const [copied, setCopied] = useState(false); const [completedAt, setCompletedAt] = useState('');
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null); const submitting = useRef(false);
  const source = sourceAccounts.find(a => a.id === 'daily')!; const amount = Number(amountText); const kind = destinationKind(destination); const method = methods.find(m => m.id === methodId); const fee = method?.fee || 0; const iban = destinationIban(destination); const resolvedDestination = method ? methodDestination(method.id, destination) : destination;
  const matches = recipients.filter(r => (filter === 'all' || filter === r.kind) && (!query || r.name.includes(query) || r.value.includes(cleanDestination(query))));
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
  function go(next: Step) { setErrors({}); if(next === 'method'){setMethodOpen(true);return;}setStep(next); }
  function back() { if (step === 'processing') return; if (step === 'receipt' || step === 'destination') onClose(); else go(step === 'confirm' ? 'amount' : steps[steps.indexOf(step) - 1]); }
  function chooseDestination() {
    const candidate = cleanDestination(destination || query); const nextKind = destinationKind(candidate);
    if (!nextKind) { setErrors({ destination: 'شماره کارت ۱۶ رقمی، شبای IR و ۲۴ رقم، یا سپردهٔ ۱۰ تا ۱۴ رقمی وارد کنید.' }); return; }
    if (candidate === source.card || candidate === source.number) { setErrors({ destination: 'مقصد نمی‌تواند همان حساب مبدا باشد.' }); return; }
    setDestination(candidate); if (!recipients.some(r => r.value === candidate)) setRecipientName('گیرندهٔ نمایشی'); go('amount');
  }
  function chooseAmount() { if (!Number.isSafeInteger(amount) || amount < 10000 || amount > source.balance) { setErrors({ amount: 'مبلغ باید حداقل ۱۰٬۰۰۰ ریال و حداکثر برابر موجودی حساب باشد.' }); return; } setMethodId(''); setMethodOpen(true); }
  function chooseMethod(next: Method) { if (methodError(next, kind, amount, source.balance)) return; setMethodOpen(false); setMethodId(next.id); setCvv(''); setMonth(''); setYear(''); setOtp(''); setOtpRequested(false); go('confirm'); }
  function submit() {
    if (submitting.current || !method) return;
    const e: Record<string,string> = {}; const eligibility = methodError(method, kind, amount, source.balance); if (eligibility) e.form = eligibility;
    if (method.id === 'card') { if (!/^\d{3,4}$/.test(cvv)) e.cvv = 'CVV2 باید ۳ یا ۴ رقم باشد.'; if (!/^(0[1-9]|1[0-2])$/.test(month)) e.month = 'ماه ۰۱ تا ۱۲'; if (!/^\d{2}$/.test(year)) e.year = 'سال دو رقمی'; }
    if (!(isValidCardOtp(otp) || otpRequested && otp === DEMO_OTP)) e.otp = 'رمز نادرست یا منقضی شده است. رمز معتبر کارت یا کد آزمایشی ۱۲۳۴۵۶ را پس از دریافت وارد کنید.';
    setErrors(e); if (Object.keys(e).length) return;
    submitting.current = true; go('processing'); timer.current = setTimeout(() => { setCompletedAt(new Date().toLocaleString('fa-IR')); onComplete({title:`انتقال وجه به ${recipientName}`,value:`${money(amount)} ریال`,icon:'transfer',details:[['مقصد',persianDigits(formattedDestination(resolvedDestination))],['مبدا',persianDigits(source.number)],['روش انتقال',method.title],['کارمزد',`${money(fee)} ریال`],['شرح',description||'—']]}); setCvv(''); setOtp(''); go('receipt'); }, 1600);
  }
  const receiptText = `رسید نمایشی تایم‌بانک\nبدون انتقال واقعی وجه\nگیرنده: ${recipientName}\nحساب مبدا: ${source.title} · ${source.number}\nمقصد: ${formattedDestination(resolvedDestination)}\nمبلغ: ${money(amount)} ریال\nروش: ${method?.title}\nکارمزد نمونه: ${money(fee)} ریال\nزمان: ${completedAt}\nپیگیری نمونه: DEMO-198730953\nشرح: ${description || '—'}`;
  async function copyReceipt() { try { await navigator.clipboard.writeText(receiptText); setCopied(true); } catch { setErrors({ copy: 'کپی خودکار در دسترس نیست. از دریافت رسید استفاده کنید.' }); } }
  function downloadReceipt() { const url = URL.createObjectURL(new Blob([receiptText], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'timebank-demo-receipt.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function destinationCard(editable = true, showIban = false) { const saved = recipients.find(r => r.value === destination); return <div className="transfer-account destination-card"><RecipientAvatar name={recipientName} src={saved?.avatar} /><div><small>به {kind ? kindLabels[kind] : 'مقصد'}</small><strong>{recipientName}</strong><span dir="ltr">{persianDigits(formattedDestination(destination))}</span>{showIban && kind === 'card' && iban && <span className="destination-iban" dir="ltr"><b>شبا</b>{persianDigits(formattedDestination(iban))}</span>}</div>{editable && <button className="text-button" onClick={() => go('destination')}>ویرایش</button>}</div>; }
  const title = {destination:'انتقال وجه',amount:'مبلغ انتقال',method:'روش انتقال',confirm:'تأیید انتقال',processing:'در حال انجام انتقال',receipt:'رسید انتقال وجه'}[step];
  return <><div className="transfer-view" inert={methodOpen}><FlowShell variant="transfer-compact" title={title} subtitle={step === 'destination' ? 'مقصد انتقال را انتخاب کنید.' : step === 'amount' ? 'چه مبلغی می‌خواهید منتقل کنید؟' : undefined} stepKey={step} onBack={back} onClose={onClose} progress={step === 'receipt' ? 100 : (steps.indexOf(step) + 1) * 20}>
    {step === 'destination' && <>
      <div className="flow-form destination-input transfer-surface"><MaterialField label="نام، شماره کارت، شبا یا سپرده" value={query} error={errors.destination} onChange={e => { setQuery(latinDigits(e.target.value)); setDestination(''); }} autoComplete="off" /></div>
      <div className="transfer-filters" aria-label="نوع مقصد">{(['all','card','account','iban'] as const).map(k => <button key={k} aria-pressed={filter === k} className={filter === k ? 'selected' : ''} onClick={() => setFilter(k)}>{k === 'all' ? 'همه' : `به ${kindLabels[k]}`}</button>)}</div>
      <h2 className="flow-section-label">مقصدهای ذخیره‌شده <small>اطلاعات نمونه</small></h2><div className="recipients-list">{matches.length ? matches.map(r => <ListRow className={destination === r.value ? 'selected' : ''} key={r.id} buttonProps={{ 'aria-pressed': destination === r.value }} onClick={() => { setDestination(r.value); setQuery(''); setRecipientName(r.name); setErrors({}); }} title={r.name} subtitle={<>{kindLabels[r.kind]} · <b dir="ltr">{persianDigits(formattedDestination(r.value))}</b></>} leading={<RecipientAvatar name={r.name} src={r.avatar} />} trailing={<i>{destination === r.value ? '✓' : ''}</i>} />) : <p className="sheet-description">مقصد ذخیره‌شده‌ای پیدا نشد. شمارهٔ کامل را وارد کنید.</p>}</div>
      <ActionButton className="flow-button" onClick={chooseDestination}>ادامه</ActionButton><p className="sheet-note">شماره‌ها و اطلاعات گیرنده در این نسخه نمونه هستند.</p></>}
    {step === 'amount' && <>{destinationCard(true, true)}<div className="transfer-surface amount-surface"><div className="transfer-amount-entry"><MaterialField label="مبلغ انتقال" value={amountText ? money(amount) : ''} dir="ltr" inputMode="numeric" maxLength={18} onChange={e => setAmountText(digits(e.target.value))} error={errors.amount} trailing={<Icon name="rial" />} /><p>{amountText ? `${money(Math.floor(amount / 10))} تومان` : 'مبلغ را به ریال وارد کنید'}</p></div><div className="amount-suggestions">{[5000000,10000000,20000000].map(n => <button key={n} onClick={() => setAmountText(String(n))}>{money(n/10)} تومان</button>)}</div></div><ActionButton className="flow-button" onClick={chooseAmount}>انتخاب روش انتقال</ActionButton></>}
    {step === 'confirm' && <>{destinationCard(false)}<div className="confirm-summary"><div><span>مبلغ انتقال</span><strong>{money(amount)} ریال</strong></div><div><span>کارمزد نمونه</span><b>{money(fee)} ریال</b></div><div><span>برداشت نمایشی</span><strong>{money(amount + fee)} ریال</strong></div><button className="text-button" onClick={() => go('method')}>{method?.title} · تغییر روش</button></div><div className="flow-form transfer-surface credentials-surface">{method?.id === 'card' && <><div className="credentials-row"><MaterialField label="CVV2" value={cvv} type="password" inputMode="numeric" maxLength={4} dir="ltr" autoComplete="off" error={errors.cvv} onChange={e => setCvv(digits(e.target.value))} /><div className="field-pair"><MaterialField label="ماه انقضا" value={month} dir="ltr" inputMode="numeric" maxLength={2} error={errors.month} onChange={e => setMonth(digits(e.target.value))} /><MaterialField label="سال انقضا" value={year} dir="ltr" inputMode="numeric" maxLength={2} error={errors.year} onChange={e => setYear(digits(e.target.value))} /></div></div><button className="demo-fill" onClick={() => { setCvv('123'); setMonth('12'); setYear('09'); }}>درج اطلاعات کارت آزمایشی</button></>}<DynamicOtpField value={otp} onChange={setOtp} error={errors.otp} onRequest={()=>setOtpRequested(true)} /><label className="transfer-description">شرح تراکنش (اختیاری)<textarea value={persianDigits(description)} maxLength={100} onChange={e=>setDescription(latinDigits(e.target.value))}/></label></div>{errors.form && <p role="alert" className="camera-error">{errors.form}</p>}<ActionButton className="flow-button" onClick={submit}>انتقال نمایشی {money(amount)} ریال</ActionButton><p className="sheet-note">اطلاعات واقعی کارت وارد نکنید. این دکمه پولی منتقل نمی‌کند.</p></>}
    {step === 'processing' && <div className="processing-panel" role="status"><div className="processing-spinner" /><h2>در حال ثبت انتقال نمایشی…</h2><p>هیچ درخواستی به شبکهٔ بانکی ارسال نمی‌شود.</p></div>}
    {step === 'receipt' && <><div className="receipt-card"><div className="receipt-top"><SuccessAnimation/><span className="receipt-status">انتقال نمایشی موفق</span><h2>{recipientName}</h2><p className="receipt-destination" dir="ltr">{persianDigits(formattedDestination(resolvedDestination))}</p><div className="receipt-amount"><strong>{money(amount)}</strong><Icon name="rial" /></div></div><div className="receipt-dashed" /><div className="receipt-bottom"><dl className="receipt-details"><div><dt>حساب مبدا</dt><dd>{source.title}</dd></div><div><dt>شماره حساب مبدا</dt><dd dir="ltr">{persianDigits(source.number)}</dd></div><div><dt>کارت مبدا</dt><dd dir="ltr">•••• {persianDigits(source.card.slice(-4))}</dd></div><div><dt>روش انتقال</dt><dd>{method?.title}</dd></div><div><dt>زمان و تاریخ</dt><dd>{completedAt}</dd></div><div><dt>پیگیری نمونه</dt><dd dir="ltr">DEMO-198730953</dd></div><div><dt>کارمزد نمونه</dt><dd>{money(fee)} ریال</dd></div><div><dt>شرح تراکنش</dt><dd>{description || '—'}</dd></div></dl><p className="sheet-note">رسید نمایشی است و اعتبار بانکی ندارد.</p></div></div><div className="button-stack receipt-actions"><ActionButton className="flow-button receipt-copy" onClick={copyReceipt} leading={<Icon name="copy" size={20} />}>{copied ? 'رسید کپی شد' : 'کپی رسید'}</ActionButton>{errors.copy && <p role="alert">{errors.copy}</p>}<ActionButton variant="secondary" className="flow-button secondary" onClick={downloadReceipt}>دریافت رسید</ActionButton></div><button className="switch-auth" onClick={onClose}>بازگشت به تایم‌بانک</button></>}
  </FlowShell></div><AnimatePresence>{methodOpen&&<BottomSheet title="روش انتقال وجه" onClose={()=>setMethodOpen(false)} className="transfer-method-sheet"><div className="amount-summary"><strong>{money(amount)}</strong><Icon name="rial" /><button className="text-button" onClick={() => {setMethodOpen(false);go('amount');}}>ویرایش مبلغ</button></div><div className="transfer-methods">{methods.map(m => { const reason = methodError(m,kind,amount,source.balance); return <button key={m.id} disabled={!!reason} onClick={() => chooseMethod(m)}><span className="service-icon">{m.id === 'time' ? <img className="timebank-method-logo" src="/assets/imgGroup2.svg" width="25" height="25" alt="نشان تایم‌بانک" /> : ['pol','paya','satna'].includes(m.id)?<img src={`/assets/${m.id}.svg`} width="25" height="25" alt=""/>:<Icon name="card"/>} </span><span><strong>{m.title}</strong><small>{reason || `${m.caption} · کارمزد ${money(m.fee)} ریال`}</small></span><Icon name="chevron" size={15} /></button>; })}</div><div className="demo-callout">کارمزدها، سقف‌ها و زمان تسویه در این پروتوتایپ نمونه هستند و مقررات بانکی محسوب نمی‌شوند.</div></BottomSheet>}</AnimatePresence></>;
}
